# Generated by Django 3.0 on 2020-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200620_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('EG', 'Egypt')], default='EG', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('EGP', 'Egyptian Pound')], default='EGP', max_length=3),
        ),
    ]
